### ISSUE TITLE
ValueError when running run.py

### ISSUE THREAD

**Issue by VMReyes** [powerhouseofthecell/machine_feeling#1]
When I run run.py, I get this error:

> Using TensorFlow backend.
Found 9 images belonging to 3 classes.
Found 34 images belonging to 3 classes.
[+] Data successfully loaded
[+] Model successfully compiled in 0.035 seconds
Epoch 1/15
Traceback (most recent call last):
  File "run.py", line 142, in <module>
    train_model(args['rounds'])
  File "run.py", line 82, in train_model
    m.train()
  File "C:\Users\Victor\Desktop\machine_feeling-master\machine_feeling-master\src\sample\ml\ml_model.py", line 32, in wrapper
    f(*args, **kwargs)
  File "C:\Users\Victor\Desktop\machine_feeling-master\machine_feeling-master\src\sample\ml\ml_model.py", line 41, in wrapper
    f(*args, **kwargs)
  File "C:\Users\Victor\Desktop\machine_feeling-master\machine_feeling-master\src\sample\ml\ml_model.py", line 207, in train
    use_multiprocessing=multiprocessing
  File "C:\Users\Victor\Anaconda3\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Victor\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py", line 1121, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Victor\Anaconda3\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Victor\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 2042, in fit_generator
    class_weight=class_weight)
  File "C:\Users\Victor\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1756, in train_on_batch
    check_batch_axis=True)
  File "C:\Users\Victor\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1382, in _standardize_user_data
    exception_prefix='target')
  File "C:\Users\Victor\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 144, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected dense_2 to have shape (None, 2) but got array with shape (9, 3)

**Comment by VMReyes** [comment]
Fixed by changing the final layer's parameters from (num_classes,...) to (3,...) where 3 is the number of classes I had. Unsure why fixed it.
